### ISSUE TITLE
Fatal ERROR！！！The program crashed when the livox-series-lidar was input into the system.

### ISSUE THREAD

**Issue by KJ-Falloutlast** [JokerJohn/PALoc#16]
Hello Dr. Hu,

Thank you very much for your contributions to the SLAM community. While we were testing PaLoc with a Livox LiDAR, we encountered the following two issues:

1. We modified the configuration file to set the algorithm for the Livox LiDAR type and then ran the program directly, using the hku.bag dataset for testing. At this point, the program crashed immediately with the following error.
![image](https://github.com/user-attachments/assets/df6ebfbe-8fb3-4e32-9958-46a918dfa7dc)

2. In order to resolve the issue mentioned in 1, we made the following modifications:
* In preprocess.cpp, we changed `fast_lio::CustomMsg::ConstPtr` to `livox_ros_driver::CustomMsg::ConstPtr`.
* Similarly, in the fastlio.cpp file, we also changed `fast_lio::CustomMsg::CustomMsg::ConstPtr` to `livox_ros_driver::CustomMsg::ConstPtr`. After completing these changes, we encountered the following error. 
![image](https://github.com/user-attachments/assets/94536e31-e57a-4254-8cbc-41608824561e)
Could you please tell us what might be causing this issue and how we can resolve it?

**Comment by JokerJohn** [comment]
@KJ-Falloutlast 

From your log, it seems that the `fastlio` node crashed, so I don't think the second modification is necessary for now. You can try commenting out the `pgo_localization` node in the launch file and running it again to confirm if the issue is with the `fastlio` node. Additionally, please pay attention to spacing issues in the YAML file. Avoid arbitrary formatting or removing parameters. If you still can't resolve the issue, you can send me a test bag snippet along with the prior map, intrinsic, and extrinsic parameters, and I can help adapt it for you.

**Comment by KJ-Falloutlast** [comment]
@JokerJohn Dr. Hu,

Thank you very much for your quick reply.

1. I commented out the pgo_localization node and ran PaLoc again to confirm if it was an issue with the fastlio node. The preprocess module still uses `fast_lio::CustomMsg::ConstPtr`. As shown in the previous result, the program crashed again with the following error: 
![image](https://github.com/user-attachments/assets/20ceb08f-6ee8-4217-9980-92721917e344)

2. Currently, I am using the [hku_campus_seq_03.bag](https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2YvYy8zZTcxNWI3YWExMzYxOTFhL0VxcEs3UW5ONE9wQ3FIbUwyeWtwWjUwQmp6M3B5SjBrd3l2d3BCQkx0elI0YlE%5FZT1UcVBOOEU&id=3E715B7AA136191A%21s09ed4aaae0cd42eaa8798bdb2929679d&cid=3E715B7AA136191A) dataset. My avia.yaml configuration file is as follows:
```yaml
common:
  lid_topic: "/livox/lidar"
  imu_topic: "/livox/imu"
  acc_cov: 0.1
  gyr_cov: 0.1
  b_acc_cov: 0.0001
  b_gyr_cov: 0.0001
  extrinsic_T: [ 0.04165, 0.02326, -0.0284 ]
  extrinsic_R: [ 1, 0, 0,
                  0, 1, 0,
                  0, 0, 1]

  odom_link: "camera_init"
  scan_filter_size: 0.1
  map_viewer_size: 0.2
  map_saved_size: 0.1

  useImuFrame: true                        # When we use IMU frame, we will get dense color cloud
  useLoopClosure: true                      # If we enable loop closure

  # Save data
  saveResultBag: false
  saveResultBodyFrame: true
  saveKeyFrame: false                     # Include color point cloud frame and raw distorted point cloud

  # Initial pose
  initial_pose: [ 1, 0, 0, 0,
                  0, 1, 0, 0,
                  0, 0, 1, 0,
                  0.000000, 0.000000, 0.000000, 1.000000 ]

lio:
  lidar_type: 1                          # 1 for Livox LiDAR series, 2 for Velodyne LiDAR, 3 for Ouster LiDAR,
  scan_line: 6
  scan_rate: 10                         # Only needs to be set for Velodyne, unit: Hz,
  timestamp_unit: 0                     # Unit of time/t field in PointCloud2 rostopic: 0-second, 1-millisecond, 2-microsecond, 3-nanosecond.
  blind: 4                            # Remove the nearest point cloud

  fov_degree: 90
  det_range: 450.0

  point_filter_num: 1
  max_iteration: 3
  filter_size_corner: 0.1
  filter_size_surf: 0.1
  filter_size_map: 0.2
  cube_side_length: 1000


pgo:
  SKIP_FRAMES: 5                                    # Map visualization, every x frames we add it to the global map and publish it
  useRawCloud: true                                 # Do not use if there is no raw cloud
  showDegeneracy: true                             # False: show uncertainty; True: show degeneracy

  useGlobalPrior: false
  icpO3dType: 2                                    # 0: ICP 1: Point-to-plane 2: GICP
  degeneracy_thres: 50
  correspondence_dis: 0.8                          # Stair_bob: 0.6;
  map_radius: 40
  map_filter_size: 0.1                             # Indoor: 0.1, Outdoor: 0.2

  loopZOffset: 2.0                                 # For stairs, if z_offset is larger than 2.0, we do not detect a loop
  historyKeyframeSearchRadius: 10.0
  historyKeyframeSearchTimeDiff: 40.0
  historyKeyframeSearchNum: 25
  loopFitnessScoreThreshold: 0.3
  loopClosureFrequency: 1                         # Detect more loops by setting this higher
  filterDis: 0.5                                  # Do not add loops if the distance between consecutive nodes is less than 10m
  filterNodeNum: 10                               # Do not detect loops every 10 nodes for each loop detection method
I believe the possible causes of the problem are:

There might be issues within the avia_handler function in the preprocess.cpp file.
The processing function for Livox point clouds livox_pcl_cbk in fastlio.cpp might have problems.
The UndistortPcl function in IMU_processing.hpp might be problematic.
In the next steps, I will thoroughly check the above three files to identify and resolve the issues. Once I find a solution, I will inform you immediately.Currently, I am using the [hku_campus_seq_03.bag](https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2YvYy8zZTcxNWI3YWExMzYxOTFhL0VxcEs3UW5ONE9wQ3FIbUwyeWtwWjUwQmp6M3B5SjBrd3l2d3BCQkx0elI0YlE%5FZT1UcVBOOEU&id=3E715B7AA136191A%21s09ed4aaae0cd42eaa8798bdb2929679d&cid=3E715B7AA136191A) dataset. My avia.yaml configuration file is as follows:
yaml

common:
  lid_topic: "/livox/lidar"
  imu_topic: "/livox/imu"
  acc_cov: 0.1
  gyr_cov: 0.1
  b_acc_cov: 0.0001
  b_gyr_cov: 0.0001
  extrinsic_T: [ 0.04165, 0.02326, -0.0284 ]
  extrinsic_R: [ 1, 0, 0,
                  0, 1, 0,
                  0, 0, 1]

  odom_link: "camera_init"
  scan_filter_size: 0.1
  map_viewer_size: 0.2
  map_saved_size: 0.1

  useImuFrame: true                        # When we use IMU frame, we will get dense color cloud
  useLoopClosure: true                      # If we enable loop closure

  # Save data
  saveResultBag: false
  saveResultBodyFrame: true
  saveKeyFrame: false                     # Include color point cloud frame and raw distorted point cloud

  # Initial pose
  initial_pose: [ 1, 0, 0, 0,
                  0, 1, 0, 0,
                  0, 0, 1, 0,
                  0.000000, 0.000000, 0.000000, 1.000000 ]

lio:
  lidar_type: 1                          # 1 for Livox LiDAR series, 2 for Velodyne LiDAR, 3 for Ouster LiDAR,
  scan_line: 6
  scan_rate: 10                         # Only needs to be set for Velodyne, unit: Hz,
  timestamp_unit: 0                     # Unit of time/t field in PointCloud2 rostopic: 0-second, 1-millisecond, 2-microsecond, 3-nanosecond.
  blind: 4                            # Remove the nearest point cloud

  fov_degree: 90
  det_range: 450.0

  point_filter_num: 1
  max_iteration: 3
  filter_size_corner: 0.1
  filter_size_surf: 0.1
  filter_size_map: 0.2
  cube_side_length: 1000


pgo:
  SKIP_FRAMES: 5                                    # Map visualization, every x frames we add it to the global map and publish it
  useRawCloud: true                                 # Do not use if there is no raw cloud
  showDegeneracy: true                             # False: show uncertainty; True: show degeneracy

  useGlobalPrior: false
  icpO3dType: 2                                    # 0: ICP 1: Point-to-plane 2: GICP
  degeneracy_thres: 50
  correspondence_dis: 0.8                          # Stair_bob: 0.6;
  map_radius: 40
  map_filter_size: 0.1                             # Indoor: 0.1, Outdoor: 0.2

  loopZOffset: 2.0                                 # For stairs, if z_offset is larger than 2.0, we do not detect a loop
  historyKeyframeSearchRadius: 10.0
  historyKeyframeSearchTimeDiff: 40.0
  historyKeyframeSearchNum: 25
  loopFitnessScoreThreshold: 0.3
  loopClosureFrequency: 1                         # Detect more loops by setting this higher
  filterDis: 0.5                                  # Do not add loops if the distance between consecutive nodes is less than 10m
  filterNodeNum: 10                               # Do not detect loops every 10 nodes for each loop detection method
```
I believe the possible causes of the problem are:

1. There might be issues within the `avia_handler` function in the preprocess.cpp file.
2. The processing function for Livox point clouds `livox_pcl_cbk` in fastlio.cpp might have problems.
3. The UndistortPcl function in `IMU_processing.hpp` might be problematic.
In the next steps, I will thoroughly check the above three files to identify and resolve the issues. Once I find a solution, I will inform you immediately.
